import { Product } from '@/types/product'

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Jabłka',
    unit: 'kg',
    stalls: ['stall1', 'stall3'],
    category: 'fruits',
    availability: 'available',
    updatedAt: '2024-03-20T10:00:00Z',
    minQuantity: 5,
    description: 'Świeże jabłka z lokalnej uprawy',
    imageUrl: '/images/products/apples.jpg',
    supplier: 'Sadownictwo Kowalski',
    purchasePrice: 2.50,
    sku: 'FR-APP-001'
  },
  {
    id: '2',
    name: 'Gruszki',
    unit: 'kg',
    stalls: ['stall1', 'stall2'],
    category: 'fruits',
    availability: 'available',
    updatedAt: '2024-03-20T10:00:00Z',
    minQuantity: 3,
    description: 'Słodkie gruszki konferencja',
    imageUrl: '/images/products/pears.jpg',
    supplier: 'Sadownictwo Nowak',
    purchasePrice: 3.20,
    sku: 'FR-PEA-001'
  },
  {
    id: '3',
    name: 'Śliwki',
    unit: 'kg',
    stalls: ['stall1'],
    category: 'fruits',
    availability: 'low_stock',
    updatedAt: '2024-03-20T10:00:00Z',
    minQuantity: 2,
    description: 'Śliwki węgierki',
    imageUrl: '/images/products/plums.jpg',
    supplier: 'Sadownictwo Wiśniewski',
    purchasePrice: 4.00,
    sku: 'FR-PLU-001'
  },
  {
    id: '4',
    name: 'Brzoskwinie',
    unit: 'szt',
    stalls: ['stall1', 'stall3'],
    category: 'fruits',
    availability: 'unavailable',
    updatedAt: '2024-03-20T10:00:00Z',
    minQuantity: 10,
    description: 'Soczyste brzoskwinie',
    imageUrl: '/images/products/peaches.jpg',
    supplier: 'Sadownictwo Kowalski',
    purchasePrice: 1.80,
    sku: 'FR-PEA-002'
  },
  {
    id: '5',
    name: 'Morele',
    unit: 'kg',
    stalls: ['stall1'],
    category: 'fruits',
    availability: 'available',
    updatedAt: '2024-03-20T10:00:00Z',
    minQuantity: 2,
    description: 'Słodkie morele',
    imageUrl: '/images/products/apricots.jpg',
    supplier: 'Sadownictwo Nowak',
    purchasePrice: 6.50,
    sku: 'FR-APR-001'
  },
  {
    id: '6',
    name: 'Maliny',
    unit: 'op',
    stalls: ['stall2'],
    category: 'berries',
    availability: 'available',
    updatedAt: '2024-03-20T10:00:00Z',
    minQuantity: 5,
    description: 'Świeże maliny',
    imageUrl: '/images/products/raspberries.jpg',
    supplier: 'Plantacja Jagodowa',
    purchasePrice: 9.00,
    sku: 'BE-RAS-001'
  },
  {
    id: '7',
    name: 'Truskawki',
    unit: 'kg',
    stalls: ['stall2'],
    category: 'berries',
    availability: 'available',
    updatedAt: '2024-03-20T10:00:00Z',
    minQuantity: 3,
    description: 'Słodkie truskawki',
    imageUrl: '/images/products/strawberries.jpg',
    supplier: 'Plantacja Jagodowa',
    purchasePrice: 7.00,
    sku: 'BE-STR-001'
  },
  {
    id: '8',
    name: 'Czereśnie',
    unit: 'kg',
    stalls: ['stall1', 'stall3'],
    category: 'fruits',
    availability: 'available',
    updatedAt: '2024-03-20T10:00:00Z',
    minQuantity: 2,
    description: 'Słodkie czereśnie',
    imageUrl: '/images/products/cherries.jpg',
    supplier: 'Sadownictwo Kowalski',
    purchasePrice: 12.00,
    sku: 'FR-CHE-001'
  },
  {
    id: '9',
    name: 'Wiśnie',
    unit: 'kg',
    stalls: ['stall1'],
    category: 'fruits',
    availability: 'available',
    updatedAt: '2024-03-20T10:00:00Z',
    minQuantity: 3,
    description: 'Kwaśne wiśnie',
    imageUrl: '/images/products/sour-cherries.jpg',
    supplier: 'Sadownictwo Nowak',
    purchasePrice: 5.50,
    sku: 'FR-CHE-002'
  },
  {
    id: '10',
    name: 'Borówki',
    unit: 'op',
    stalls: ['stall2'],
    category: 'berries',
    availability: 'low_stock',
    updatedAt: '2024-03-20T10:00:00Z',
    minQuantity: 4,
    description: 'Świeże borówki',
    imageUrl: '/images/products/blueberries.jpg',
    supplier: 'Plantacja Jagodowa',
    purchasePrice: 10.00,
    sku: 'BE-BLU-001'
  }
] 